{% set name = "upstash-redis" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/upstash_redis-{{ version }}.tar.gz
  sha256: e3b77205cb99695b8000042695f8054e27c12fbc2eebe5ccdd428d986b11de87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - httpx >=0.23.0,<1
    - python >={{ python_min }},<4.0.0
    - aiohttp >=3.8.4,<4.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - upstash_redis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/upstash/redis-python
  summary: Serverless Redis SDK from Upstash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
